version: "3.9"

services:
  app:
    container_name: ai-server-express
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_DIR=/app/logs
      - SECRET_KEY=${SECRET_KEY}
      - CREDENTIALS=true
      - ORIGIN=https://ai-server-express-u14194.vm.elestio.app
      - LOG_FORMAT=combined
    restart: always

  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - DOMAIN=ai-server-express-u14194.vm.elestio.app
    depends_on:
      - app
    restart: always